int64 timestamp
float32 left_analog_x
float32 left_analog_y
float32 right_analog_x
float32 right_analog_y
float32 right_trigger
float32 left_trigger
float32 dpad_x
float32 dpad_y
int8 button_a
int8 button_b
int8 button_2 #not used
int8 button_x
int8 button_y
int8 button_5 #not used
int8 button_l1
int8 button_r1
int8 button_l2
int8 button_r2
int8 button_select
int8 button_start
int8 button_12 #not used
int8 button_left_analog
int8 button_right_analog
int8 button_15 #not used
